# Generated by Django 4.2 on 2023-06-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='skip_length',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
