# Generated by Django 4.2 on 2023-07-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_memory_skip_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='current_count',
            field=models.IntegerField(default=1),
        ),
    ]
