# Generated by Django 4.2.4 on 2023-09-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0006_alter_memory_current_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="add_audio",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
